

# This file was *autogenerated* from the file ex4.4.sage
from sage.all_cmdline import *   # import sage library

_sage_const_20 = Integer(20); _sage_const_3 = Integer(3)
group = Zmod(_sage_const_20 ).unit_group()
group.order(_sage_const_3 )

