

# This file was *autogenerated* from the file 2.3.1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_123456789 = Integer(123456789)
n = _sage_const_123456789 
factors = factor(n)
print(factors)

